
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SESI_SENAI
 */
public class CassinoJorges extends javax.swing.JFrame {
    private String nome;
    private int valor_entrada = 0;
    private int fichas_compradas = 0;
    private int quantidade_fichas_10;
    private int quantidade_fichas_50;
    private int quantidade_fichas_100;
    private int quantidade_fichas_500;
    private int quantidade_fichas_1000;
    private int quantidade_fichas_5000;
    private int troco = 0;
    /**
     * Creates new form CassinoJorges
     */
    public CassinoJorges() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campo_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campo_valor_entrada = new javax.swing.JTextField();
        jorge_10_botao = new javax.swing.JButton();
        jorge_100_botao = new javax.swing.JButton();
        jorge_50_botao = new javax.swing.JButton();
        jorge_1000_botao = new javax.swing.JButton();
        jorge_500_botao = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jorge_5000_botao = new javax.swing.JButton();
        jorgesLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        trocoLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jButton4.setText("jButton2");

        jButton6.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Jorge's Cassino");

        campo_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("Valor de entrada:");

        campo_valor_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_valor_entradaActionPerformed(evt);
            }
        });

        jorge_10_botao.setText("J$ 10");
        jorge_10_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorge_10_botaoActionPerformed(evt);
            }
        });

        jorge_100_botao.setText("J$ 100");
        jorge_100_botao.setMaximumSize(new java.awt.Dimension(61, 32));
        jorge_100_botao.setMinimumSize(new java.awt.Dimension(61, 32));
        jorge_100_botao.setPreferredSize(new java.awt.Dimension(61, 32));
        jorge_100_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorge_100_botaoActionPerformed(evt);
            }
        });

        jorge_50_botao.setText("J$ 50");
        jorge_50_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorge_50_botaoActionPerformed(evt);
            }
        });

        jorge_1000_botao.setText("J$ 1.000");
        jorge_1000_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorge_1000_botaoActionPerformed(evt);
            }
        });

        jorge_500_botao.setText("J$ 500");
        jorge_500_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorge_500_botaoActionPerformed(evt);
            }
        });

        jLabel4.setText("Jorges:");

        jorge_5000_botao.setText("J$ 5.000");
        jorge_5000_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorge_5000_botaoActionPerformed(evt);
            }
        });

        jLabel6.setText("Troco:");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Jogar!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campo_nome)
                            .addComponent(campo_valor_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jorgesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(trocoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jorge_10_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jorge_50_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jorge_100_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jorge_500_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jorge_1000_botao, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jorge_5000_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campo_valor_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addComponent(trocoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jorgesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jorge_10_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jorge_100_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jorge_50_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jorge_500_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jorge_1000_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jorge_5000_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jorge_50_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorge_50_botaoActionPerformed
        int valor_ficha = 50;
        if(troco >= valor_ficha){
            quantidade_fichas_50 = quantidade_fichas_50 + 1;
        }
            compraFichas(valor_ficha);
    }//GEN-LAST:event_jorge_50_botaoActionPerformed

    private void campo_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nomeActionPerformed
        nome = campo_nome.getText();
        JOptionPane.showMessageDialog(null, nome);
    }//GEN-LAST:event_campo_nomeActionPerformed

    private void campo_valor_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_valor_entradaActionPerformed
        valor_entrada = Integer.parseInt(campo_valor_entrada.getText());
        jorgesLabel.setText(Integer.toString(fichas_compradas));
        troco = valor_entrada - fichas_compradas;
        trocoLabel.setText(Integer.toString(troco));
    }//GEN-LAST:event_campo_valor_entradaActionPerformed

    private void jorge_10_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorge_10_botaoActionPerformed
        int valor_ficha = 10;
        if(troco >= valor_ficha){
            quantidade_fichas_10 = quantidade_fichas_10 + 1;
        }
            compraFichas(valor_ficha);
        
    }//GEN-LAST:event_jorge_10_botaoActionPerformed

    private void jorge_100_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorge_100_botaoActionPerformed
        int valor_ficha = 100;
        if(troco >= valor_ficha){
            quantidade_fichas_100 = quantidade_fichas_100 + 1;
        }
            compraFichas(valor_ficha);
    }//GEN-LAST:event_jorge_100_botaoActionPerformed

    private void jorge_500_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorge_500_botaoActionPerformed
        int valor_ficha = 500;
        if(troco >= valor_ficha){
            quantidade_fichas_500 = quantidade_fichas_500 + 1;  
        } 
        compraFichas(valor_ficha);
    }//GEN-LAST:event_jorge_500_botaoActionPerformed

    private void jorge_1000_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorge_1000_botaoActionPerformed
        int valor_ficha = 1000;
        if(troco >= valor_ficha){
            quantidade_fichas_1000 = quantidade_fichas_1000 + 1;
        }
        compraFichas(valor_ficha);
    }//GEN-LAST:event_jorge_1000_botaoActionPerformed

    private void jorge_5000_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorge_5000_botaoActionPerformed
        int valor_ficha = 5000;
        if(troco >= valor_ficha){
            quantidade_fichas_5000 = quantidade_fichas_5000 + 1;
        }
        compraFichas(valor_ficha);
    }//GEN-LAST:event_jorge_5000_botaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuJogos frame = new MenuJogos();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CassinoJorges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CassinoJorges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CassinoJorges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CassinoJorges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CassinoJorges().setVisible(true);
            }
        });
    }
    
    public void compraFichas(int valor_ficha){
        if (troco >= valor_ficha){
            fichas_compradas = fichas_compradas + valor_ficha;
            troco = troco - valor_ficha;
            jorgesLabel.setText(Integer.toString(fichas_compradas));
            trocoLabel.setText(Integer.toString(troco));
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem 💰 suficientes... Seu pobre!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo_nome;
    private javax.swing.JTextField campo_valor_entrada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jorge_1000_botao;
    private javax.swing.JButton jorge_100_botao;
    private javax.swing.JButton jorge_10_botao;
    private javax.swing.JButton jorge_5000_botao;
    private javax.swing.JButton jorge_500_botao;
    private javax.swing.JButton jorge_50_botao;
    private javax.swing.JLabel jorgesLabel;
    private javax.swing.JLabel trocoLabel;
    // End of variables declaration//GEN-END:variables
}
